### ISSUE TITLE
Objects as Instance

### ISSUE THREAD

**Issue by MMetze** [MMetze/DMHelper-Tracker#41] opened 2019-09-14 04:56 UTC
**Discord User:**
@novas#2602

**Is your feature request related to a problem? Please describe.**
Adding objects alongside Npcs, to track them in the adventure. Also have the utility to add them fast to an encounter and being able to get moved around (ie carriage, chair, desk). 

**Describe the solution you'd like**
Same like for npc, but without the stats block and maybe just a description and an ac/hp field for combat stuff. Or an xml interpreted view for customisation. 

**Describe alternatives you've considered**
Working with npcs as objects would be possible.

**Comment by dm-helper** [comment] 2021-01-14 16:59
Considered part of the Templates solution in #105

**Comment by dm-helper** [comment] 2021-01-14 17:00
Duplicate of #33

**Closed by dm-helper** 2021-01-14 17:00 UTC
Labels: Utility Tools, effort-low, feature request
