### ISSUE TITLE
[FEAT REQ] Random Event Tables

### ISSUE THREAD

**Issue by DrkNinja** [MMetze/DMHelper-Tracker#25] opened 2019-08-27 03:54 UTC
**Discord User:**
DMHelper (Dev)

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
The sort of thing where I can define a table, then click on the name, and it'll roll a result from the table.

e.g. Party has an airship malfunction
Malfunctiuon Outcomes
Engine Out
Rudder Locked
Weapon Destroyed
Module Destroyed etcetc

Then you just click the table and it pulls something out of it at random.

Essentially pulling a random outcome out of a hat blindly.

**Describe alternatives you've considered**
N/A You're the dev.

**Additional context**
Dev Suggestion

**Comment by mybigfriendjo** [comment] 2019-08-27 05:37
Duplicate of #9

**Closed** 2019-08-27 09:57 UTC
Labels: feature request
