### ISSUE TITLE
Condition Labels in Combat

### ISSUE THREAD

**Issue by DrkNinja** [MMetze/DMHelper-Tracker#61] opened 2020-02-19 23:14 UTC
**Discord User:**
๖DrkNinja#7015

**Is your feature request related to a problem? Please describe.**
Unclear condition status' during combat

**Describe the solution you'd like**
A label that appears above the mobs, maybe different color variations, and single letters 

**Describe alternatives you've considered**
A label that appears when targeting a mob

**Additional context**
High priority

**Comment by dm-helper** [comment] 2020-04-10 15:35
@DrkNinja is this a duplicate of https://github.com/MMetze/DMHelper-Tracker/issues/81 ? If yes, please delete one of them...

**Comment by dm-helper** [comment] 2021-01-14 16:11
Closed as a duplicate of #81

**Closed as completed by dm-helper** 2021-01-14 16:11 UTC
Labels: feature request, effort-medium, Core, Combat
